$ErrorActionPreference = "Stop"

Write-Host ""
Write-Host "HIIRAGI HITSUGI - Twitch Worker Setup" -ForegroundColor Cyan
Write-Host "Client ID is already configured." -ForegroundColor DarkGray
Write-Host "The Client Secret is sent only to Cloudflare and is not saved in this project." -ForegroundColor DarkGray
Write-Host ""

if (-not (Get-Command node -ErrorAction SilentlyContinue)) {
    throw "Node.js was not found. Install the LTS version of Node.js, then run this script again."
}

if (-not (Get-Command npm -ErrorAction SilentlyContinue)) {
    throw "npm was not found. Reinstall the LTS version of Node.js, then run this script again."
}

Set-Location $PSScriptRoot

Write-Host "[1/6] Installing Wrangler..." -ForegroundColor Yellow
npm install

Write-Host "[2/6] Signing in to Cloudflare..." -ForegroundColor Yellow
Write-Host "A browser window may open. Approve the Cloudflare authorization." -ForegroundColor DarkGray
npx wrangler login

Write-Host "[3/6] Creating the Worker..." -ForegroundColor Yellow
$initialOutput = (& npx wrangler deploy 2>&1 | Out-String)
Write-Host $initialOutput

Write-Host "[4/6] Registering TWITCH_CLIENT_SECRET..." -ForegroundColor Yellow
Write-Host "Paste the Client Secret at the Wrangler prompt. The input may not be displayed." -ForegroundColor DarkGray
Write-Host "Do not paste the secret into index.html, GitHub, or this chat." -ForegroundColor DarkGray
npx wrangler secret put TWITCH_CLIENT_SECRET

Write-Host "[5/6] Publishing the final Worker version..." -ForegroundColor Yellow
$deployOutput = (& npx wrangler deploy 2>&1 | Out-String)
Write-Host $deployOutput

$combinedOutput = $initialOutput + "`n" + $deployOutput
$urlMatch = [regex]::Match($combinedOutput, 'https://[a-zA-Z0-9._-]+\.workers\.dev')
if (-not $urlMatch.Success) {
    Write-Host ""
    Write-Host "The Worker was deployed, but its URL could not be detected automatically." -ForegroundColor Yellow
    $workerUrl = Read-Host "Paste the workers.dev URL shown above"
} else {
    $workerUrl = $urlMatch.Value
}

$workerUrl = $workerUrl.Trim().TrimEnd('/')
if ($workerUrl -notmatch '^https://.+\.workers\.dev$') {
    throw "The Worker URL is invalid: $workerUrl"
}

$endpoint = "$workerUrl/latest?channel=hiragi_hitsugi"
$configPath = Join-Path $PSScriptRoot "..\js\media-config.js"
$configContent = @"
/* Generated by worker/setup-and-deploy.ps1 */
window.MEDIA_CONFIG = Object.freeze({
    twitchLatestEndpoint: "$endpoint"
});
"@

Set-Content -Path $configPath -Value $configContent -Encoding UTF8

Write-Host "[6/6] Testing the latest archive endpoint..." -ForegroundColor Yellow
try {
    $result = Invoke-RestMethod -Uri $endpoint -Method Get -TimeoutSec 30
    if ($result.ok -eq $true) {
        Write-Host "Twitch API connection succeeded." -ForegroundColor Green
        if ($null -ne $result.archive) {
            Write-Host ("Latest archive: " + $result.archive.title) -ForegroundColor Green
        } else {
            Write-Host "No public archive is currently available. The channel link fallback will be shown." -ForegroundColor Yellow
        }
    } else {
        Write-Host "The endpoint responded, but Twitch returned an error." -ForegroundColor Yellow
    }
} catch {
    Write-Host "The endpoint test failed. Confirm the Client Secret and Cloudflare deployment." -ForegroundColor Red
    Write-Host $_.Exception.Message -ForegroundColor DarkRed
}

Write-Host ""
Write-Host "Setup complete." -ForegroundColor Green
Write-Host "Worker endpoint:" -ForegroundColor Cyan
Write-Host $endpoint
Write-Host ""
Write-Host "js/media-config.js has been updated automatically." -ForegroundColor Green
Write-Host "Upload/push the project to GitHub Pages to publish the Twitch card." -ForegroundColor Cyan
